<script lang="ts">
	import Practice from '$lib/img/practice.png';
	import Webapp from '$lib/img/webapp.png';
	import Phone from '$lib/img/phone.png';
	import Exams from '$lib/img/exams.png';
	import Flashcards from '$lib/img/flashcards-main.png';
	import Quizzes from '$lib/img/quizzes.png';
	import XP from '$lib/img/gamified.png';
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';

	export let data;

	onMount(() => {
		if (data.user) {
			console.log(data.user);

			goto('/home');
		}
	});
</script>

<nav class="sticky top-0 z-50 w-full border-b bg-white/80 px-4 py-4 backdrop-blur-lg md:px-8">
	<div class="mx-auto flex max-w-7xl items-center justify-between">
		<div class="flex items-center space-x-3">
			<img src="/logo.svg" alt="Synapsis logo" class="h-10 w-10 rounded-xl" />
			<span class="text-2xl font-bold text-gray-800">Synapsis</span>
		</div>

		<div class="flex items-center space-x-6">
			<a
				href="/signup"
				class="rounded-full bg-primary px-6 py-2 text-sm font-medium text-white transition-colors hover:bg-blue-700"
			>
				Get started
			</a>
		</div>
	</div>
</nav>

<header class="bg-gradient-to-br from-blue-50 to-indigo-100">
	<div
		class="mx-auto flex min-h-[calc(100vh-4rem)] max-w-7xl flex-col items-center justify-center px-4 py-16 text-center sm:px-6 lg:px-8"
	>
		<h1
			class="mb-6 max-w-3xl text-5xl font-extrabold leading-tight text-gray-900 sm:text-6xl lg:text-7xl"
		>
			Make learning <span class="text-primary">fun</span> and
			<span class="text-indigo-600">effective</span>
		</h1>

		<p class="mb-10 max-w-2xl text-xl text-gray-600 sm:text-2xl">
			Synapsis helps you learn and retain information through interactive and engaging methods using
			AI.
		</p>

		<a
			href="/signup"
			class="group relative inline-flex items-center justify-center overflow-hidden rounded-full bg-blue-600 px-8 py-3 text-lg font-semibold text-white transition duration-300 ease-out hover:bg-gradient-to-r hover:from-blue-600 hover:to-indigo-600"
		>
			<span
				class="absolute right-0 translate-x-full transition-transform duration-300 ease-out group-hover:-translate-x-4"
			>
				<svg
					class="h-5 w-5"
					fill="none"
					stroke="currentColor"
					viewBox="0 0 24 24"
					xmlns="http://www.w3.org/2000/svg"
					><path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M13 7l5 5m0 0l-5 5m5-5H6"
					></path></svg
				>
			</span>
			<span class="transition-all duration-300 ease-out group-hover:mr-4">Get Started</span>
		</a>
	</div>
</header>

<section class="py-20">
	<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
		<h2 class="mb-12 text-center text-4xl font-bold text-gray-900 sm:text-5xl">
			Why Choose Synapsis?
		</h2>
		<p class="mx-auto mb-16 max-w-3xl text-center text-xl text-gray-600">
			Synapsis offers a variety of features designed to enhance your learning experience and improve
			information retention.
		</p>

		<div class="grid gap-10 sm:grid-cols-2 lg:grid-cols-3">
			<div class="rounded-xl bg-white p-8 shadow-lg transition-all hover:shadow-xl">
				<img src={Flashcards} alt="" class="mx-auto mb-6 w-full" />
				<h3 class="mb-4 text-2xl font-bold text-gray-900">Interactive Flashcards</h3>
				<p class="text-gray-600">
					Create and study with dynamic flashcards to memorize information quickly and effectively.
				</p>
			</div>

			<div class="rounded-xl bg-white p-8 shadow-lg transition-all hover:shadow-xl">
				<img src={Quizzes} alt="" class="mx-auto mb-6 w-full" />
				<h3 class="mb-4 text-2xl font-bold text-gray-900">AI Quizzes</h3>
				<p class="text-gray-600">
					Receive personalized quizzes generated by AI to test your knowledge and reinforce
					learning.
				</p>
			</div>

			<div class="rounded-xl bg-white p-8 shadow-lg transition-all hover:shadow-xl">
				<img src={XP} alt="" class="mx-auto mb-6 w-full" />
				<h3 class="mb-4 text-2xl font-bold text-gray-900">Gamified Learning</h3>
				<p class="text-gray-600">
					Earn XP, and climb the leaderboard as you learn and improve. Flex your knowledge muscles!
				</p>
			</div>
		</div>
	</div>
</section>

<section class="bg-gray-100 py-20">
	<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
		<h2 class="mb-12 text-center text-4xl font-bold text-gray-900 sm:text-5xl">
			Meet Synaptica - <span class="italic text-primary">based</span> Study Buddy
		</h2>

		<p class="mx-auto max-w-3xl text-center text-xl text-gray-600">
			Synaptica is your AI-powered study buddy, always ready to assist you in learning and retaining
			information through engaging and interactive methods.
		</p>

		<section>
			<div
				class="mx-auto flex w-full max-w-2xl flex-col gap-4 overflow-auto rounded-t-xl bg-base-200/20 p-4"
			>
				<div class="prose prose-sm max-w-xs rounded-xl bg-base-200 px-4">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>
							Hey there! 🌟 To boost your practice history, consider creating quizzes or flashcards
							for your notes. You have some great topics like "The product mix" and "Forms of
							business organisation" that could really benefit from these tools.
						</p>
						<p>
							Don't forget, practicing with quizzes and flashcards can help reinforce your learning.
							Keep up the great work, and let's make those notes even more interactive! You've got
							this! 💪📚
						</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!---->
				<div class="prose prose-sm ml-auto max-w-xs rounded-xl bg-primary px-4 text-white">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>thank you!</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!----><!----><!---->
				<div class="prose prose-sm max-w-xs rounded-xl bg-base-200 px-4">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>
							You're welcome! If you need any help or have questions, just let me know. Happy
							studying! 😊📖
						</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!---->
				<div class="prose prose-sm ml-auto max-w-xs rounded-xl bg-primary px-4 text-white">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>can i get a few points for that?</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!----><!----><!---->
				<div class="prose prose-sm max-w-xs rounded-xl bg-base-200 px-4">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>
							I appreciate your enthusiasm! I can't give points directly, but I can reward you for
							your engagement and motivation. Keep up the great work, and you'll see the benefits in
							no time! 🌟
						</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!---->
				<div class="prose prose-sm ml-auto max-w-xs rounded-xl bg-primary px-4 text-white">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>yes you can</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!----><!----><!---->
				<div class="prose prose-sm max-w-xs rounded-xl bg-base-200 px-4">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>
							I understand, but I can only reward points based on your progress and engagement. Keep
							practicing, and you'll earn them along the way! You're doing great! 😊✨
						</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!---->
				<div class="prose prose-sm ml-auto max-w-xs rounded-xl bg-primary px-4 text-white">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>what can i practice then?</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!----><!----><!---->
				<div class="prose prose-sm max-w-xs rounded-xl bg-base-200 px-4">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>
							You can practice by creating quizzes or flashcards for your notes! Here are some
							suggestions:
						</p>
						<ol>
							<li><strong>Create a quiz</strong> for "The product mix."</li>
							<li>
								<strong>Make flashcards</strong> for "Forms of business organisation" or "The purpose
								of Business Activity."
							</li>
						</ol>
						<p>
							Let me know which one you'd like to start with, and I can help you set it up! 📚💡
						</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!---->
				<div class="prose prose-sm ml-auto max-w-xs rounded-xl bg-primary px-4 text-white">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>yeah do the 1st one</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!----><!----><!----><!----><!----><!----><!----><!---->
				<div class="max-w-xs rounded-xl border bg-white p-4 shadow">
					<!----><!----><!----><!---->
					<h4 class="mb-4 text-xl font-bold text-black">New Quiz<!----></h4>
					<!---->
					<!----><button
						class="
        btn relative overflow-hidden
        
        

			
    "
						type="button"
						><div><!----><!---->Make quiz<!----></div>
						<div class="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"><!----></div>
						<!----></button
					><!---->
					<p class="mt-2">Good luck!</p>
				</div>
				<!----><!----><!----><!---->
				<div class="prose prose-sm ml-auto max-w-xs rounded-xl bg-primary px-4 text-white">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>i did it</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!---->
				<div class="prose prose-sm max-w-xs rounded-xl bg-base-200 px-4">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>Great job on completing the quiz! 🎉 You scored 33/100.</p>
						<p>
							Don't be discouraged; it's a good starting point! Review the questions you found
							challenging, and try again when you're ready. Keep practicing, and you'll improve!
							💪📚
						</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!---->
				<div class="prose prose-sm ml-auto max-w-xs rounded-xl bg-primary px-4 text-white">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>ok, can you help me with memorization?</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!----><!----><!---->
				<div class="prose prose-sm max-w-xs rounded-xl bg-base-200 px-4">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>No worries! Here are a few tips to help with memorization:</p>
						<ol>
							<li>
								<strong>Break it down</strong>: Divide the material into smaller sections and focus
								on one at a time.
							</li>
							<li>
								<strong>Use flashcards</strong>: Create flashcards for key concepts and terms to
								reinforce your memory.
							</li>
							<li>
								<strong>Teach it</strong>: Explain the material to someone else; teaching helps
								solidify your understanding.
							</li>
							<li>
								<strong>Practice regularly</strong>: Revisit the material frequently to keep it
								fresh in your mind.
							</li>
						</ol>
						<p>Would you like to create some flashcards for better memorization? 😊📖</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!---->
				<div class="prose prose-sm ml-auto max-w-xs rounded-xl bg-primary px-4 text-white">
					<div class="carta-viewer carta-theme__default markdown-body">
						<p>Create flashcards for it then</p>
						<!---->
					</div>
					<!---->
				</div>
				<!----><!----><!----><!----><!----><!----><!----><!----><!----><!---->
				<div class="svelte-1di4xm2 max-w-xs rounded-xl border bg-white p-4 shadow">
					<!----><!----><!----><!---->
					<h4 class="mb-4 text-xl font-bold text-black">Make Flashcards<!----></h4>
					<!---->
					<!----><button
						class="
        btn relative overflow-hidden
        
        

			
    "
						type="button"
						><div><!----><!---->Make flashcards<!----></div>
						<div class="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"><!----></div>
						<!----></button
					><!---->
					<p class="mt-2">Good luck!</p>
				</div>
				<!----><!----><!---->
				<!---->
				<div class="h-10"></div>
			</div>
		</section>
	</div>
</section>

<section class="py-20">
	<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
		<h2 class="mb-12 text-center text-4xl font-bold text-gray-900 sm:text-5xl">
			Practice Makes Perfect
		</h2>

		<p class="mx-auto max-w-3xl text-center text-xl text-gray-600">
			Track your progress and see how you improve over time through consistent practice with quizzes
			and flashcards.
		</p>

		<img src={Practice} alt="Practice" class="mx-auto mt-12 max-w-full rounded-xl shadow-xl" />
	</div>
</section>

<section class="bg-gradient-to-br from-indigo-50 to-blue-100 py-20">
	<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
		<h2 class="mb-12 text-center text-4xl font-bold text-gray-900 sm:text-5xl">
			Learn Anytime, Anywhere
		</h2>

		<div class="mx-auto flex max-w-4xl items-end">
			<div class="mockup-browser border bg-base-300">
				<div class="mockup-browser-toolbar">
					<div class="input">https://synapsis.posandu.com/home</div>
				</div>
				<img src={Webapp} alt="Web App" class="w-full" />
			</div>

			<div>
				<div class="mockup-phone">
					<div class="camera"></div>
					<div class="display">
						<img src={Phone} alt="Mobile App" class="w-full object-cover" />
					</div>
				</div>
			</div>
		</div>

		<p class="mx-auto mt-12 max-w-3xl text-center text-xl text-gray-600">
			Access Synapsis on your phone, tablet, or computer. Seamlessly continue your learning journey
			across all devices with the speed of a native app!
		</p>
	</div>
</section>

<section class="py-20">
	<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
		<h2 class="mb-12 text-center text-4xl font-bold text-gray-900 sm:text-5xl">
			Ace Your Exams with Confidence
		</h2>

		<p class="mx-auto mb-12 max-w-3xl text-center text-xl text-gray-600">
			Get a comprehensive overview of your study progress and identify areas that need more
			attention.
		</p>

		<img src={Exams} alt="Exam Overview" class="mx-auto max-w-full rounded-xl shadow-xl" />
	</div>
</section>

<section class="bg-gray-100 py-20">
	<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
		<h2 class="mb-12 text-center text-4xl font-bold text-gray-900 sm:text-5xl">
			Effortless Note Digitization
		</h2>

		<p class="mx-auto mb-12 max-w-3xl text-center text-xl text-gray-600">
			Transform your handwritten notes into digital format with our AI-powered OCR technology. Save
			time and reduce errors in the process.
		</p>

		<iframe
			width="560"
			height="315"
			src="https://www.youtube.com/embed/uflurlBNCuk?si=I5s1bGF76crmX9Gv"
			title="YouTube video player"
			frameborder="0"
			allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
			referrerpolicy="strict-origin-when-cross-origin"
			allowfullscreen
			class="mx-auto rounded-xl shadow-xl"
			loading="lazy"
		></iframe>
	</div>
</section>

<section class="py-20">
	<div class="mx-auto max-w-7xl px-4 text-center sm:px-6 lg:px-8">
		<h2 class="mb-12 text-center text-4xl font-bold text-gray-900 sm:text-5xl">
			Impressed? Get Started Today!
		</h2>

		<p class="mx-auto mb-12 max-w-3xl text-center text-xl text-gray-600">
			Join Synapsis today and start your learning journey with our interactive and engaging study
			tools.
		</p>

		<a
			href="/signup"
			class="group relative mx-auto inline-flex items-center justify-center overflow-hidden rounded-full bg-primary px-8 py-3 text-lg font-semibold text-white transition duration-300 ease-out hover:bg-gradient-to-r hover:from-blue-600 hover:to-indigo-600"
		>
			<span
				class="absolute right-0 translate-x-full transition-transform duration-300 ease-out group-hover:-translate-x-4"
			>
				<svg
					class="h-5 w-5"
					fill="none"
					stroke="currentColor"
					viewBox="0 0 24 24"
					xmlns="http://www.w3.org/2000/svg"
					><path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M13 7l5 5m0 0l-5 5m5-5H6"
					></path></svg
				>
			</span>
			<span class="transition-all duration-300 ease-out group-hover:mr-4">Get Started</span>
		</a>
	</div>
</section>

<footer class="bg-gray-900 py-12 text-white">
	<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
		<div class="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
			<div>
				<h3 class="mb-4 text-lg font-semibold">Synapsis</h3>
				<p class="text-gray-400">Making learning fun and effective.</p>
			</div>
		</div>
		<div class="mt-8 border-t border-gray-800 pt-8 text-center text-gray-400">
			2024 Synapsis. Created by <a href="https://posandu.com" class="text-primary">Posandu</a> for
			the
			<a href="https://hashnode.com/hackathons/ai-for-tomorrow?source=ai" class="text-primary"
				>AI for Tomorrow</a
			> hackathon.
		</div>
	</div>
</footer>
